version: '3.5'
 ########################################################
 #
 # Use
 #      docker-compose up
 #
 # Exported ports
 #   - 172.16.208.10     6379  => redis
 #   - 172.16.208.15     7000  => redis-commander
 #   - 172.16.208.20     5432  => postgres
 #   - 172.16.208.30     5050  => gpadmin4

networks:
  backend:
    name: farmu_backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.208.0/24

services:

  redis:
    image: 'redis:6.2.2'
    restart: "no"
    ports:
      - '6379:6379'
    networks:
      backend:
        ipv4_address: 172.16.208.10

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: "no"
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - '7000:8081'
    networks:
      backend:
        ipv4_address: 172.16.208.15

  postgres:
    image: 'postgres:14.4'
    restart: "no"
    volumes:
      - './.data/postgres_data:/var/lib/postgresql/data'
      - './docker-compose/docker-compose-init-postgres.sh:/docker-entrypoint-initdb.d/init-db.sh'
      - ./docker-compose/:/mnt
    environment:
      - POSTGRES_DB=farmu
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=1234
    ports:
      - '5432:5432'
    networks:
      backend:
        ipv4_address: 172.16.208.20

  flyway_shortener:
    image: flyway/flyway:8.5
    networks:
      backend:
        ipv4_address: 172.16.208.21
    volumes:
      - ./url-shortener-service/db-scripts/target/classes/release_0.1/:/flyway/sql
      - ./docker-compose/:/mnt
    depends_on:
      - postgres
    entrypoint: ["/mnt/wait-for-it.sh", "postgres:5432", "-t", "300", "--", "/mnt/docker-compose-run-flyway.sh", "deployer", "1234", "farmu_shortener" ] 

  pgadmin4:
    image: 'thajeztah/pgadmin4'
    restart: "no"
    ports:
      - '5050:5050'
    depends_on: 
      - 'postgres'
    networks:
      backend:
        ipv4_address: 172.16.208.30

  url-shortener:
    image: 'farmu/url-shortener:1.0-SNAPSHOT'
    environment:
      - PORT=8080
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_SCHEMA=farmu_shortener
      - DATABASE_USER=url_shortener_service
      - DATABASE_PASSWORD=1234
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: "no"
    ports:
      - '8080:8080'
    networks:
      backend:
        ipv4_address: 172.16.208.50
    depends_on:
      - 'redis'
      - 'postgres'
    volumes:
      - ./:/mnt
    working_dir: /mnt
    command: ["/mnt/wait-for-it.sh", "postgres:5432", "-t", "600", "--", "/bin/ls"]

