psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $TEST_USER WITH ENCRYPTED PASSWORD '$TEST_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $TEST_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $TEST_USER;

    CREATE USER url_shortener_service WITH ENCRYPTED PASSWORD '1234';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO url_shortener_service;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO url_shortener_service;
EOSQL
