CREATE USER url_shortener_service WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';
CREATE USER deployer WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN ENCRYPTED PASSWORD 'TO_BE_REPLACED';

GRANT deployer TO pgadmin;
CREATE DATABASE farmu_shortener WITH OWNER deployer;
REVOKE deployer FROM pgadmin;

