
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: farmu-services-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.url_shortener_service_ingress_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: url-shortener-service
                port:
                  number: 80
    - host: {{ .Values.image_resizer_service_ingress_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-resizer-service
                port:
                  number: 80

